//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRotatoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacao
    {
        public int AutCod { get; set; }
        public string VeiPla { get; set; }
        public Nullable<System.DateTime> AutDatInc { get; set; }
        public Nullable<System.DateTime> AutdatPro { get; set; }
        public Nullable<int> AutUsuInc { get; set; }
        public Nullable<System.DateTime> AutDatPas { get; set; }
        public Nullable<int> AutUsuPas { get; set; }
        public Nullable<short> AutNumEix { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
